export enum ErrorCode {
  ENTITY_ALREADY_EXISTS = 'ENTITY_ALREADY_EXISTS',
  ENTITY_NOT_FOUND = 'ENTITY_NOT_FOUND',
  ENTITY_PROPERTY_INVALID = 'ENTITY_PROPERTY_INVALID',
  ENTITY_PROPERTY_MISSING = 'ENTITY_PROPERTY_MISSING',
  ENTITY_PROPERTY_NOT_FOUND = 'ENTITY_PROPERTY_NOT_FOUND',
  ENTITY_PROPERTY_UNEXPECTED = 'ENTITY_PROPERTY_UNEXPECTED',
  QUERY_INVALID = 'QUERY_INVALID',
  TOKEN_EXPIRED_OR_INVALID = 'TOKEN_EXPIRED_OR_INVALID',
  TOKEN_NOT_FOUND = 'TOKEN_NOT_FOUND',
  UNAUTHORIZED_OPERATION = 'UNAUTHORIZED_OPERATION',
}
